# Generated by Django 5.1.3 on 2024-11-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='latest_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
