# Generated by Django 5.1.3 on 2024-11-18 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_event_researcharea'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty_members',
            field=models.ManyToManyField(blank=True, related_name='faculty_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
